import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

const PAGES = [
  {
    slug: "uae-dubai-residency", url_prefix: "move", segment: "uae_worker",
    title: "Move to Dubai — UAE Residence Permit",
    subtitle: "Get your UAE residence permit processed in 8–12 weeks. Fixed price. No surprises.",
    hero_headline: "Your UAE Residence Permit in 8–12 weeks.",
    hero_subtext: "We handle every step from job offer to stamped passport. Fixed pricing. Real timelines.",
    hero_cta_label: "Start my Dubai Move Fund", hero_cta_url: "/signup",
    destination: "UAE", category: "residency_permit",
    process_steps: [
      { step: 1, title: "We assess your eligibility", body: "You complete a short profile. We confirm your employer is MOHRE-registered and your documents are ready. Takes 24 hours." },
      { step: 2, title: "Entry permit application", body: "Your employer submits through the MOHRE portal. We guide every step. Entry permit issued in 2–4 weeks." },
      { step: 3, title: "Medical examination", body: "Completed at a UAE-approved health centre within your first week in Dubai." },
      { step: 4, title: "Emirates ID biometrics", body: "Appointment at an ICP centre. Takes 30 minutes. ID arrives within 5–7 working days." },
      { step: 5, title: "Residence permit stamped", body: "Your passport is stamped with a 2-year residence permit. You are now a UAE resident." },
    ],
    requirements: ["Valid passport — minimum 6 months validity", "Signed employment contract from UAE employer", "Educational certificates (notarised in Nigeria + UAE embassy attested)", "Bank statement — 3 months", "Passport photographs — white background, biometric", "Police clearance certificate"],
    faqs: [
      { q: "Do I need a job offer before starting?", a: "Yes for the employment route. Your employer must be registered with UAE MOHRE. We verify this before you pay anything." },
      { q: "Can my family join me?", a: "Yes. Once your residence permit is issued you can sponsor your spouse and children. Salary threshold applies." },
      { q: "How long is the residence permit valid?", a: "Standard employment permits are 2 years, renewable. UAE Golden Visa is 5 or 10 years." },
      { q: "Do I need to be in UAE during the process?", a: "Yes. The medical examination and Emirates ID biometrics require your physical presence in UAE." },
      { q: "What if my application is rejected?", a: "Less than 6% of our UAE applications are rejected. We refund the service fee less document preparation costs and explain exactly why." },
    ],
    cost_calculator_destination: "UAE", cost_calculator_service_type: "residency",
    success_story_name: "Chukwuemeka A.", success_story_role: "Petroleum Engineer, now UAE resident",
    success_story_quote: "I spent 6 months trying to figure this out on my own. Swiipt did it in 10 weeks. The cost breakdown they showed me before I started was exactly what I paid.",
    success_story_destination: "Dubai, UAE",
    meta_title: "UAE Residence Permit for Nigerians 2026 — Swiipt",
    meta_description: "Get your UAE residence permit processed in 8–12 weeks. Fixed pricing, real timelines. Trusted by Nigerian professionals moving to Dubai.",
    published: false,
  },
  {
    slug: "qatar-work-visa", url_prefix: "move", segment: "qatar_worker",
    title: "Qatar Work Visa & Residence Permit",
    subtitle: "Process your Qatar work visa and residence permit in 6–12 weeks. Fixed price.",
    hero_headline: "Qatar Work Visa processed in 6–12 weeks.",
    hero_subtext: "Employer-sponsored. We coordinate everything between you, your employer, and the Qatar government portal.",
    hero_cta_label: "Start my Qatar Visa Fund", hero_cta_url: "/signup",
    destination: "Qatar", category: "work_visa",
    process_steps: [
      { step: 1, title: "Employment verification", body: "We confirm your Qatar employer is a registered sponsor on the MADLSA portal. This takes 24–48 hours." },
      { step: 2, title: "Work entry visa", body: "Your employer applies for your entry visa. Issued in 2–3 weeks. Required before you can enter Qatar." },
      { step: 3, title: "Medical examination", body: "Completed within 7 days of arriving in Qatar at a MOPH-approved centre. We book your appointment." },
      { step: 4, title: "Fingerprinting + RP issuance", body: "Biometrics taken at a government centre. Residence Permit card ready in 3–5 working days." },
    ],
    requirements: ["Valid passport — minimum 6 months validity", "Signed employment contract", "Educational certificates (attested)", "Passport photographs", "Medical fitness certificate (done in Qatar after arrival)"],
    faqs: [
      { q: "Who pays for the Qatar visa?", a: "By law, your employer pays Qatar government visa fees. Our service fee covers coordination and processing support." },
      { q: "Can my family come to Qatar?", a: "Yes, if your monthly salary meets the family sponsorship threshold (typically QAR 10,000+). We advise on this during assessment." },
      { q: "Is Qatar right for me vs UAE?", a: "Qatar has lower competition for professional roles, slightly lower cost of living, and strong demand in oil and gas, engineering, healthcare, and education." },
    ],
    cost_calculator_destination: "Qatar", cost_calculator_service_type: "visa",
    success_story_name: "Adaeze N.", success_story_role: "Nurse, now Qatar resident",
    success_story_quote: "The process was intimidating until Swiipt broke it down step by step. My residence permit came through in 9 weeks.",
    success_story_destination: "Doha, Qatar",
    meta_title: "Qatar Work Visa for Nigerians 2026 — Swiipt",
    meta_description: "Process your Qatar work visa and residence permit in 6–12 weeks. Fixed pricing. Trusted by Nigerian professionals moving to Doha.",
    published: false,
  },
  {
    slug: "canada-express-entry", url_prefix: "move", segment: "canada_seeker",
    title: "Canada Express Entry & Permanent Residency",
    subtitle: "Build your Express Entry profile, maximise your CRS score, and manage your full PR application.",
    hero_headline: "Canada Permanent Residency — done properly.",
    hero_subtext: "We assess your CRS score, advise on improvement strategies, and manage your full application from profile to landing.",
    hero_cta_label: "Start my Canada PR Fund", hero_cta_url: "/signup",
    destination: "Canada", category: "residency_permit",
    process_steps: [
      { step: 1, title: "Profile assessment", body: "We calculate your CRS score and identify every point improvement opportunity." },
      { step: 2, title: "Express Entry profile creation", body: "We build your profile on the IRCC portal with optimised descriptions for maximum points." },
      { step: 3, title: "CRS improvement strategy", body: "If your score needs improvement, we advise on IELTS retake, provincial nomination targeting, or job offer strategies." },
      { step: 4, title: "Invitation to Apply (ITA)", body: "When a draw matches your score, you receive an ITA. We have a 72-hour window to accept it." },
      { step: 5, title: "Application submission", body: "We compile and submit all documents within the 60-day post-ITA window." },
      { step: 6, title: "COPR and landing", body: "Confirmation of Permanent Residence issued. We brief you on your landing requirements." },
    ],
    requirements: ["IELTS Academic or General (CLB 7 minimum)", "Educational Credential Assessment (ECA) from WES", "Work experience reference letters on company letterhead", "Police clearance certificate", "Medical examination by designated panel physician", "Proof of funds: CAD 13,757 for single applicant"],
    faqs: [
      { q: "What CRS score do I need?", a: "Recent all-programs draws have had cutoffs between 480–540. We assess your current score and show you how many points you are away." },
      { q: "What is PNP and is it better than Express Entry?", a: "Provincial Nominee Program often has lower cutoffs. A successful nomination adds 600 CRS points — virtually guaranteeing an ITA." },
      { q: "How long does the whole process take?", a: "From profile creation to landing in Canada: typically 18–30 months." },
      { q: "Do I need a job offer?", a: "No, but a valid offer from a Canadian employer adds 50–200 points depending on the role level." },
    ],
    cost_calculator_destination: "Canada", cost_calculator_service_type: "residency",
    success_story_name: "Oluwafemi A.", success_story_role: "Software Engineer, now Canadian PR",
    success_story_quote: "My CRS was 471 when I came to Swiipt. They identified two PNP streams I qualified for. I received my ITA 4 months later.",
    success_story_destination: "Toronto, Canada",
    meta_title: "Canada Express Entry for Nigerians 2026 — Swiipt",
    meta_description: "Build your Canada Express Entry profile and manage your full PR application. CRS score assessment, PNP pathways, and step-by-step guidance.",
    published: false,
  },
  {
    slug: "canada-provincial-nominee", url_prefix: "move", segment: "canada_seeker",
    title: "Canada Provincial Nominee Program (PNP)",
    subtitle: "The faster route to Canada PR for applicants with CRS scores below 500.",
    hero_headline: "Canada PR through Provincial Nomination.",
    hero_subtext: "Many Nigerian professionals qualify for PNP streams that nobody tells them about. We identify your strongest province and manage the full process.",
    hero_cta_label: "Start my Canada PR Fund", hero_cta_url: "/signup",
    destination: "Canada", category: "residency_permit",
    process_steps: [
      { step: 1, title: "Province matching", body: "We assess your occupation, experience, and profile against active PNP streams across all 10 provinces." },
      { step: 2, title: "Provincial application", body: "We build and submit your provincial nomination application. Processing: 2–8 months." },
      { step: 3, title: "Nomination certificate", body: "Province issues your nomination certificate. This adds 600 points to your CRS score." },
      { step: 4, title: "Express Entry ITA", body: "With 600 added points you will receive an ITA at the next Express Entry draw." },
      { step: 5, title: "Full PR application", body: "We compile and submit your complete PR application within the 60-day window." },
    ],
    requirements: ["IELTS results (CLB 7 minimum)", "Educational Credential Assessment (ECA)", "Work experience documentation", "Provincial application documents (vary by province)", "Police clearance certificate", "Medical examination"],
    faqs: [
      { q: "Which provinces are best for Nigerians?", a: "Ontario, British Columbia, Alberta, and Saskatchewan have active PNP streams with high acceptance rates for healthcare, tech, and trades." },
      { q: "How does PNP differ from Express Entry?", a: "In Express Entry you wait for a draw matching your CRS score. In PNP a province nominates you and adds 600 points — guaranteeing an ITA." },
      { q: "What occupations qualify?", a: "Healthcare, engineering, IT, accounting, education, and skilled trades all have strong PNP demand." },
    ],
    cost_calculator_destination: "Canada", cost_calculator_service_type: "residency",
    success_story_name: "Dr. Chidinma O.", success_story_role: "Pharmacist, now Ontario resident",
    success_story_quote: "My CRS was 458. Express Entry would have taken years. Swiipt matched me to Ontario PNP for healthcare workers. I had my nomination in 5 months.",
    success_story_destination: "Toronto, Canada",
    meta_title: "Canada PNP for Nigerians 2026 — Swiipt",
    meta_description: "Get to Canada faster through Provincial Nominee Program. We identify your strongest province and manage the full nomination application.",
    published: false,
  },
  {
    slug: "uk-skilled-worker", url_prefix: "move", segment: "uk_worker",
    title: "UK Skilled Worker Visa",
    subtitle: "Work legally in the UK with a path to Indefinite Leave to Remain after 5 years.",
    hero_headline: "UK Skilled Worker Visa — managed end to end.",
    hero_subtext: "We coordinate with your UK employer, prepare all documents, and guide you through every Home Office requirement.",
    hero_cta_label: "Start my UK Move Fund", hero_cta_url: "/signup",
    destination: "UK", category: "work_visa",
    process_steps: [
      { step: 1, title: "Employer + CoS verification", body: "We verify your UK employer holds a valid Tier 2 sponsorship licence." },
      { step: 2, title: "Document preparation", body: "We prepare your full application pack: TB test, IELTS results, financial evidence, and identity documents." },
      { step: 3, title: "Visa application submission", body: "Application submitted through UKVI. We complete the online form with you." },
      { step: 4, title: "Biometric appointment", body: "Attended at a UK Visa Application Centre in Lagos or Abuja." },
      { step: 5, title: "Decision and travel", body: "Standard processing: 8–10 weeks. Priority: 5–10 working days." },
    ],
    requirements: ["Valid passport — minimum 6 months beyond intended stay", "Certificate of Sponsorship from UK employer", "IELTS Life Skills (B1 minimum)", "Tuberculosis test certificate", "Bank statements showing £1,270 for 28 consecutive days", "Educational certificates"],
    faqs: [
      { q: "Do I need a job offer before applying?", a: "Yes. The UK Skilled Worker visa requires a Certificate of Sponsorship from a UK employer." },
      { q: "What is the minimum salary?", a: "£26,200 per year or the going rate for the specific occupation, whichever is higher." },
      { q: "Can my family come with me?", a: "Yes. Your spouse and children under 18 can apply as dependants." },
    ],
    cost_calculator_destination: "UK", cost_calculator_service_type: "visa",
    success_story_name: "Blessing O.", success_story_role: "NHS Nurse, now UK resident",
    success_story_quote: "I had the job offer but had no idea what to do next. Swiipt walked me through every document and my visa came in 7 weeks.",
    success_story_destination: "London, UK",
    meta_title: "UK Skilled Worker Visa for Nigerians 2026 — Swiipt",
    meta_description: "Process your UK Skilled Worker visa end to end. Certificate of Sponsorship guidance, document preparation, and biometric appointment support.",
    published: false,
  },
  {
    slug: "uk-healthcare-nursing-jobs", url_prefix: "work", segment: "uk_healthcare",
    title: "UK Healthcare & NHS Jobs for Nigerian Professionals",
    subtitle: "NMC registration, UK Skilled Worker visa, and NHS job placement — all in one service.",
    hero_headline: "Move to the UK as a Nigerian healthcare professional.",
    hero_subtext: "We partner with NHS-approved recruitment agencies to help you find your role and process your visa.",
    hero_cta_label: "Start my NHS Career Fund", hero_cta_url: "/signup",
    destination: "UK", category: "work_visa",
    process_steps: [
      { step: 1, title: "NMC eligibility assessment", body: "We review your nursing or medical qualifications against NMC/GMC requirements." },
      { step: 2, title: "IELTS / OET preparation", body: "Healthcare professionals need IELTS Academic 7.0+ in each component." },
      { step: 3, title: "NHS employer matching", body: "We refer you to NHS recruitment partners who actively place Nigerian nurses." },
      { step: 4, title: "CBT/OSCE preparation (nurses)", body: "NMC Computer Based Test and OSCE required for non-UK trained nurses." },
      { step: 5, title: "Visa processing", body: "UK Health and Care Worker visa — faster and cheaper than standard Skilled Worker route." },
    ],
    requirements: ["Valid passport", "Nigerian nursing or medical degree certificate", "Current NMCN / MDCN registration", "IELTS Academic 7.0+ (or OET B+)", "Reference letters", "Good standing letter from NMCN/MDCN"],
    faqs: [
      { q: "Does my employer pay visa fees?", a: "Many NHS trusts pay the visa fee, IHS, and flights for internationally recruited staff." },
      { q: "How long does NMC registration take?", a: "Typically 12–18 months from application to NMC pin." },
      { q: "What salary can I expect?", a: "NHS Band 5 starting salary: £28,407–£34,581/year." },
    ],
    cost_calculator_destination: "UK", cost_calculator_service_type: "visa",
    success_story_name: "Ngozi K.", success_story_role: "Registered Nurse, now working at NHS Trust",
    success_story_quote: "I did not know about the Health and Care Worker visa route. Swiipt handled everything.",
    success_story_destination: "Manchester, UK",
    meta_title: "UK NHS Jobs for Nigerian Nurses and Doctors — Swiipt",
    meta_description: "NMC registration guidance, NHS job matching, and UK Health and Care Worker visa processing for Nigerian healthcare professionals.",
    published: false,
  },
  {
    slug: "uk-company-registration", url_prefix: "business", segment: "entrepreneur",
    title: "UK Company Registration — Receive Stripe & International Payments",
    subtitle: "Register a UK Limited Company in 3–7 business days and unlock global payment access.",
    hero_headline: "Receive Stripe payments legally. Register your UK company in days.",
    hero_subtext: "Nigerian freelancers cannot use Stripe with Nigerian accounts. A UK Ltd company solves this immediately.",
    hero_cta_label: "Register my UK company", hero_cta_url: "/signup",
    destination: "UK", category: "company_registration",
    process_steps: [
      { step: 1, title: "Document collection", body: "We need your passport, preferred company name, and director details." },
      { step: 2, title: "Companies House filing", body: "We prepare and submit your incorporation documents. Standard: 24–48 hours." },
      { step: 3, title: "Certificate of incorporation", body: "You receive your certificate by email. Your UK company is legally registered." },
      { step: 4, title: "Stripe + banking setup guidance", body: "Step-by-step instructions for Wise Business and Stripe." },
    ],
    requirements: ["Valid passport (scanned copy)", "Proposed company name", "Director residential address (Nigerian address accepted)", "Shareholder details"],
    faqs: [
      { q: "Do I need to travel to the UK?", a: "No. The entire process is remote." },
      { q: "Will I pay UK tax?", a: "If you are not a UK resident with no UK activities, UK corporation tax typically does not apply." },
      { q: "How do I receive Stripe payments?", a: "Open a Wise Business account under your UK company. Stripe pays into Wise, you transfer to Nigeria." },
    ],
    cost_calculator_destination: "UK", cost_calculator_service_type: "company",
    success_story_name: "Taiwo F.", success_story_role: "Freelance Developer",
    success_story_quote: "I lost three clients because I could not accept Stripe. My UK company was registered in 2 days. I now receive $8,000/month through Stripe.",
    success_story_destination: "Lagos (operating globally)",
    meta_title: "UK Company Registration for Nigerians — Receive Stripe Payments | Swiipt",
    meta_description: "Register a UK Limited Company in 3–7 days and receive Stripe and international client payments. Remote registration, no UK travel required.",
    published: false,
  },
  {
    slug: "us-llc-formation", url_prefix: "business", segment: "entrepreneur",
    title: "US LLC Registration — Access Stripe US, Mercury Bank & US Clients",
    subtitle: "Form a US LLC in Wyoming or Delaware in 5–10 business days.",
    hero_headline: "Register a US LLC and access the world's most powerful payment infrastructure.",
    hero_subtext: "A Wyoming or Delaware LLC gives you Stripe US, Mercury banking, and US client invoicing.",
    hero_cta_label: "Register my US LLC", hero_cta_url: "/signup",
    destination: "USA", category: "company_registration",
    process_steps: [
      { step: 1, title: "State selection", body: "Wyoming for most freelancers — lowest fees, strongest privacy. Delaware for VC-funded businesses." },
      { step: 2, title: "Articles of Organisation", body: "We prepare and file with the state. Processing: 3–5 business days." },
      { step: 3, title: "EIN application", body: "Employer Identification Number from the IRS. Required for US bank account and Stripe." },
      { step: 4, title: "Mercury Bank + Stripe setup", body: "Step-by-step guidance for Mercury business banking and Stripe US." },
    ],
    requirements: ["Valid passport (scanned copy)", "Proposed company name", "Registered agent address (included in service)", "Your Nigerian home address"],
    faqs: [
      { q: "What is a registered agent?", a: "A US address that receives legal documents for your LLC. Included for 1 year in our service." },
      { q: "Do I need a US address or SSN?", a: "No. Non-US residents can form a US LLC without either." },
      { q: "What is Mercury Bank?", a: "A US digital bank that accepts LLCs owned by non-US residents." },
    ],
    cost_calculator_destination: null, cost_calculator_service_type: "company",
    success_story_name: "Emeka O.", success_story_role: "SaaS Founder",
    success_story_quote: "My payment processor kept rejecting Nigerian accounts. A Wyoming LLC with Mercury took 10 days to set up.",
    success_story_destination: "Lagos (operating in USA)",
    meta_title: "US LLC Registration for Nigerians — Stripe US & Mercury Bank | Swiipt",
    meta_description: "Form a US LLC in Wyoming or Delaware. Access Stripe US, Mercury Bank, and US client invoicing. No US address or travel required.",
    published: false,
  },
  {
    slug: "grenada-citizenship-by-investment", url_prefix: "citizenship", segment: "second_passport",
    title: "Grenada Citizenship by Investment — Second Passport",
    subtitle: "One of the most powerful second passports available. Includes E-2 Treaty Visa eligibility for the USA.",
    hero_headline: "Grenada citizenship. Visa-free to 140+ countries including E-2 Treaty access to the USA.",
    hero_subtext: "The only Caribbean CBI program that includes E-2 Treaty Investor Visa eligibility.",
    hero_cta_label: "Start my Grenada Citizenship Fund", hero_cta_url: "/signup",
    destination: "Grenada", category: "second_citizenship",
    process_steps: [
      { step: 1, title: "Due diligence assessment", body: "We pre-assess your profile for any issues before you pay government fees." },
      { step: 2, title: "Application preparation", body: "Personal statement, source of funds, police clearances, medical certificate." },
      { step: 3, title: "Government submission", body: "Submitted to Grenada CIU. Processing: 4–6 months." },
      { step: 4, title: "Due diligence clearance", body: "Background checks completed. Investment made to National Transformation Fund." },
      { step: 5, title: "Passport issuance", body: "Grenada passport issued. Valid 5 years. Includes family members." },
    ],
    requirements: ["Valid Nigerian passport", "Police clearance certificates", "Medical certificate", "Proof of investment funds", "Passport photographs", "Reference letters"],
    faqs: [
      { q: "What is the minimum investment?", a: "USD 150,000 donation to the National Transformation Fund." },
      { q: "What is the E-2 Treaty benefit?", a: "As a Grenada citizen you can apply for a US E-2 Investor Visa to live in the USA." },
      { q: "Can my family be included?", a: "Yes. Spouse, children under 30, parents over 55, and siblings." },
    ],
    cost_calculator_destination: null, cost_calculator_service_type: "second_citizenship",
    success_story_name: "Babatunde A.", success_story_role: "Business Owner",
    success_story_quote: "Grenada citizenship gave me E-2 eligibility. That opened everything.",
    success_story_destination: "Lagos / USA",
    meta_title: "Grenada Citizenship by Investment for Nigerians — Swiipt",
    meta_description: "Get a Grenada second passport with E-2 Treaty access to the USA. Visa-free to 140+ countries. Managed application from Nigeria.",
    published: false,
  },
  {
    slug: "cruise-ship-jobs-visa", url_prefix: "work", segment: "cruise_worker",
    title: "Cruise Ship Jobs — Visa, Medical & STCW Training",
    subtitle: "C1/D visa, medical certificate, and STCW safety training for cruise ship employment.",
    hero_headline: "Get a cruise ship job. We handle the visa, medical, and STCW.",
    hero_subtext: "Earn in USD with free accommodation and food. We process the C1/D visa and arrange pre-departure requirements.",
    hero_cta_label: "Start my Cruise Career Fund", hero_cta_url: "/signup",
    destination: null, category: "work_visa",
    process_steps: [
      { step: 1, title: "Job offer secured", body: "Apply to cruise lines or maritime recruiters. You need a job offer before visa processing." },
      { step: 2, title: "STCW safety training", body: "Mandatory 5-day training in Lagos or Port Harcourt." },
      { step: 3, title: "Medical examination", body: "PEME at a flag-state approved medical centre." },
      { step: 4, title: "C1/D visa application", body: "US Crewmember visa for ships calling at US ports." },
      { step: 5, title: "Joining port", body: "Flights to your joining port and what to pack." },
    ],
    requirements: ["Valid passport — 2 years validity recommended", "Signed employment contract", "STCW safety certificate", "Medical fitness certificate (PEME)", "Yellow fever vaccination card"],
    faqs: [
      { q: "Do I need experience?", a: "Entry-level positions require no previous maritime experience." },
      { q: "How much do cruise workers earn?", a: "Entry-level: USD 800–1,200/month. With free food and accommodation, you can save most of it." },
      { q: "How long is a contract?", a: "Most contracts are 6–8 months followed by 2–3 months paid leave." },
    ],
    cost_calculator_destination: null, cost_calculator_service_type: null,
    success_story_name: "Olamide F.", success_story_role: "Entertainment Host, Royal Caribbean",
    success_story_quote: "Swiipt gave me a checklist and processed my visa. I have been on ships for 2 years and saved more than I ever did in Lagos.",
    success_story_destination: "Currently at sea",
    meta_title: "Cruise Ship Jobs Visa for Nigerians — C1/D & STCW | Swiipt",
    meta_description: "Get your cruise ship C1/D visa, STCW certificate, and medical clearance. Start earning USD on cruise ships.",
    published: false,
  },
  {
    slug: "germany-job-seeker-visa", url_prefix: "work", segment: "job_seeker",
    title: "Germany Opportunity Card (Chancenkarte) — Job Seeker Visa",
    subtitle: "Move to Germany for up to 1 year to find work. No job offer required.",
    hero_headline: "Move to Germany without a job offer.",
    hero_subtext: "Germany's Chancenkarte lets qualified professionals live in Germany for 12 months while job hunting.",
    hero_cta_label: "Start my Germany Fund", hero_cta_url: "/signup",
    destination: "Germany", category: "work_visa",
    process_steps: [
      { step: 1, title: "Points assessment", body: "We calculate your score from qualifications, experience, language, and age. Minimum 6 points." },
      { step: 2, title: "Qualification recognition", body: "Advice on anabin database and ENIC-NARIC recognition process." },
      { step: 3, title: "Document preparation", body: "Bank statements, health insurance, accommodation proof, language certificate." },
      { step: 4, title: "Visa application", body: "At German embassy in Abuja or Lagos. Processing: 6–12 weeks." },
      { step: 5, title: "Arrival and job search", body: "12 months to find employment. Convert to work permit without leaving Germany." },
    ],
    requirements: ["Nigerian university degree (bachelor minimum)", "Bank statements showing €1,027/month", "Health insurance for Germany", "Proof of accommodation", "CV in European format"],
    faqs: [
      { q: "Do I need to speak German?", a: "No. German skills earn extra points but many find English-language tech and engineering roles." },
      { q: "What jobs are available?", a: "Software engineering, data science, nursing, electrical engineering, accounting." },
      { q: "What if I do not find a job in 12 months?", a: "The Chancenkarte is one-time. Most holders find roles within 3–6 months." },
    ],
    cost_calculator_destination: "Germany", cost_calculator_service_type: "visa",
    success_story_name: "Ifeanyi C.", success_story_role: "Software Engineer, now Germany work permit holder",
    success_story_quote: "Germany Chancenkarte took 3 months to process. I had a job offer within 6 weeks of arriving in Munich.",
    success_story_destination: "Munich, Germany",
    meta_title: "Germany Opportunity Card (Chancenkarte) for Nigerians 2026 — Swiipt",
    meta_description: "Move to Germany for 1 year to find work. No job offer required. Chancenkarte processing for Nigerian professionals.",
    published: false,
  },
  {
    slug: "canton-fair-china-sourcing", url_prefix: "business", segment: "trade_show",
    title: "Canton Fair China Sourcing Trip — Visa & Full Package",
    subtitle: "China visa, flights, hotel near Canton Fair, and optional sourcing support.",
    hero_headline: "Canton Fair. Done properly.",
    hero_subtext: "China business visa, return flights, Guangzhou hotel, airport transfers, and optional sourcing guide.",
    hero_cta_label: "Start my Canton Fair Fund", hero_cta_url: "/signup",
    destination: "China", category: "relocation_concierge",
    process_steps: [
      { step: 1, title: "Canton Fair registration", body: "We assist with your exhibitor badge registration." },
      { step: 2, title: "China business visa (M visa)", body: "Processed at Chinese embassy in Abuja. 5–10 working days." },
      { step: 3, title: "Flights and hotel", body: "Return flights Lagos–Guangzhou and hotel near Pazhou Complex." },
      { step: 4, title: "Airport transfers + SIM card", body: "Guangzhou pickup and Chinese SIM with WeChat setup." },
      { step: 5, title: "Optional: sourcing guide", body: "Nigerian-speaking agent for fair floor and supplier negotiations." },
    ],
    requirements: ["Valid passport — 6 months validity", "Hotel booking or invitation letter", "Bank statement (USD 3,000+ recommended)", "Business registration documents", "Yellow fever vaccination card"],
    faqs: [
      { q: "When is the Canton Fair?", a: "Twice a year: April–May and October–November." },
      { q: "How much should I budget?", a: "Visa + flights + 7-night hotel + transfers: approximately ₦800,000–₦1,100,000." },
      { q: "Do I need to speak Mandarin?", a: "No. Suppliers have English-speaking staff. Optional sourcing guide is bilingual." },
    ],
    cost_calculator_destination: null, cost_calculator_service_type: null,
    success_story_name: "Akinwale M.", success_story_role: "Importer, Lagos",
    success_story_quote: "Swiipt sorted my visa, booked my hotel 5 minutes from the fair, and connected me with a sourcing agent. My cost per trip dropped by 40%.",
    success_story_destination: "Lagos / Guangzhou",
    meta_title: "Canton Fair China Trip for Nigerians — Visa & Hotel | Swiipt",
    meta_description: "Complete Canton Fair trip package for Nigerian importers. China business visa, Guangzhou hotel, flights, and optional sourcing guide.",
    published: false,
  },
  {
    slug: "portugal-digital-nomad-visa", url_prefix: "remote", segment: "digital_nomad",
    title: "Portugal D8 Digital Nomad Visa",
    subtitle: "EU residency for remote workers earning income from outside Portugal.",
    hero_headline: "Live in Portugal. Keep your remote job.",
    hero_subtext: "Portugal D8 gives you EU residency as a remote worker. After 5 years you can apply for permanent residency or citizenship.",
    hero_cta_label: "Start my Portugal Fund", hero_cta_url: "/signup",
    destination: "Portugal", category: "remote_work_visa",
    process_steps: [
      { step: 1, title: "Income documentation", body: "Proof of remote income: USD 3,600+/month." },
      { step: 2, title: "NHR tax registration", body: "Non-Habitual Resident tax regime for qualifying new residents." },
      { step: 3, title: "Document preparation", body: "Accommodation proof, NIF, health insurance, background check." },
      { step: 4, title: "Embassy application", body: "At Portuguese embassy. Processing: 6–10 weeks." },
      { step: 5, title: "AIMA registration", body: "Register with immigration authority in Portugal for residency card." },
    ],
    requirements: ["Valid passport", "Proof of remote income: €1,520/month minimum", "Accommodation proof in Portugal", "Portuguese NIF number", "Health insurance", "Criminal record certificate"],
    faqs: [
      { q: "What counts as proof of remote income?", a: "Employment contract from non-Portuguese employer, freelance agreements, or client invoices." },
      { q: "Can I work for Portuguese companies?", a: "The D8 visa is for non-Portuguese income sources only." },
      { q: "What is NHR?", a: "Non-Habitual Resident status gives qualifying residents a 20% flat tax rate for 10 years." },
    ],
    cost_calculator_destination: "Portugal", cost_calculator_service_type: "visa",
    success_story_name: "Tokunbo A.", success_story_role: "UX Designer working remotely for a UK company",
    success_story_quote: "I had been trying to figure out the Portuguese visa for 8 months. Swiipt made sense of it and my D8 came through in 9 weeks.",
    success_story_destination: "Lisbon, Portugal",
    meta_title: "Portugal D8 Digital Nomad Visa for Nigerians 2026 — Swiipt",
    meta_description: "Get your Portugal D8 digital nomad visa. EU residency for remote workers. Income requirements and application management.",
    published: false,
  },
  {
    slug: "uk-student-proof-of-funds", url_prefix: "student", segment: "student_proof",
    title: "UK Student Visa Proof of Funds — Save and Demonstrate Financial Capacity",
    subtitle: "Never lose your UK student visa because of the 28-day financial requirement.",
    hero_headline: "Never lose your UK student visa because of proof of funds again.",
    hero_subtext: "The UK Home Office requires funds in a bank account for 28 consecutive days. Swiipt's locked savings creates this documented history.",
    hero_cta_label: "Start my Study Fund", hero_cta_url: "/signup",
    destination: "UK", category: "residency_permit",
    process_steps: [
      { step: 1, title: "Calculate required amount", body: "Tuition fees + living costs. Typically £25,000–£50,000." },
      { step: 2, title: "Open a locked savings goal", body: "Create a UK Study Fund on Swiipt and begin depositing." },
      { step: 3, title: "Build 28 consecutive days", body: "Funds must be in account for 28 days before visa application." },
      { step: 4, title: "Visa application", body: "We process your UK Student visa with your CAS and financial statement." },
    ],
    requirements: ["University offer letter + CAS number", "Funds showing 28+ consecutive days", "IELTS Academic 6.0+", "Valid passport", "TB test certificate"],
    faqs: [
      { q: "How much do I need to show?", a: "Tuition + £1,334/month (London) or £1,023/month (outside London) for up to 9 months." },
      { q: "Does the money have to be in a UK bank?", a: "No. Nigerian bank statements are accepted if they show 28 consecutive days." },
      { q: "Can I use my parents' money?", a: "Yes, with a sponsorship letter and their bank statements." },
    ],
    cost_calculator_destination: null, cost_calculator_service_type: null,
    success_story_name: "Adaora N.", success_story_role: "MSc student, University of Manchester",
    success_story_quote: "My first visa was rejected because the money had only been in the account for 19 days. Swiipt's structured savings gave me the 28-day history.",
    success_story_destination: "Manchester, UK",
    meta_title: "UK Student Visa Proof of Funds for Nigerians — Swiipt",
    meta_description: "Never lose your UK student visa because of the 28-day financial requirement. Swiipt savings create documented proof of funds.",
    published: false,
  },
  {
    slug: "nysc-move-abroad-plan", url_prefix: "student", segment: "nysc",
    title: "Just Finished NYSC? Your 12-Month Plan to Move Abroad",
    subtitle: "The moment you finish NYSC is the best time to start planning your international move.",
    hero_headline: "Finished NYSC. Ready to move. Here is your plan.",
    hero_subtext: "Most Nigerian graduates complete NYSC with no clear international roadmap. This page gives you the exact pathway.",
    hero_cta_label: "Start my Move Fund", hero_cta_url: "/signup",
    destination: null, category: "residency_permit",
    process_steps: [
      { step: 1, title: "Assess your strongest pathway", body: "Canada Express Entry, UK Skilled Worker, UAE work visa, or Germany Chancenkarte." },
      { step: 2, title: "Take IELTS now", body: "Required for most pathways. Take it while your English is sharp." },
      { step: 3, title: "Start saving immediately", body: "Even ₦30,000/month over 12 months builds your financial base." },
      { step: 4, title: "Build verifiable work experience", body: "NYSC + 12 months employment qualifies you for most pathways." },
      { step: 5, title: "Order your service", body: "When savings reach 25%, unlock your eligibility assessment." },
    ],
    requirements: ["NYSC discharge certificate", "University degree certificate", "IELTS results (or plan to take IELTS)", "Employment reference letters", "Valid international passport"],
    faqs: [
      { q: "Does NYSC count as work experience?", a: "For Canada Express Entry and some other pathways, yes if the role matches your NOC." },
      { q: "What is the fastest pathway?", a: "UK company registration (5 days) or UAE work visa (8–12 weeks)." },
      { q: "Should I get more qualifications?", a: "Usually not. Your bachelor degree already qualifies you for most pathways." },
    ],
    cost_calculator_destination: null, cost_calculator_service_type: null,
    success_story_name: "Kelechi O.", success_story_role: "Corper, batch A 2025, now UAE resident",
    success_story_quote: "By month 8 of service I already had my UAE entry permit.",
    success_story_destination: "Dubai, UAE",
    meta_title: "Just Finished NYSC? Move Abroad in 12 Months — Swiipt",
    meta_description: "Your 12-month international migration plan from NYSC completion. Canada, UK, UAE, and Germany pathways for Nigerian graduates.",
    published: false,
  },
  {
    slug: "fund-your-childs-education-abroad", url_prefix: "parents", segment: "parent_funder",
    title: "Fund Your Child's International Education — Save and Prove It",
    subtitle: "UK, Canada, USA, and Australia universities require proof of funds. Start saving now.",
    hero_headline: "Give your child the international education they deserve.",
    hero_subtext: "Tuition fees, living costs, and visa proof of funds — planned, saved, and documented on Swiipt.",
    hero_cta_label: "Start my Child Education Fund", hero_cta_url: "/signup",
    destination: null, category: "residency_permit",
    process_steps: [
      { step: 1, title: "Calculate total cost", body: "UK: £25,000–£60,000/year. Canada: CAD 25,000–50,000/year." },
      { step: 2, title: "Create a locked education fund", body: "Save for 2–3 years to build documented history." },
      { step: 3, title: "Document your saving history", body: "Swiipt provides clean, documented saving records." },
      { step: 4, title: "Student visa processing", body: "When your child has an offer, we process the visa." },
    ],
    requirements: ["Bank statement showing required balance", "University offer letter and CAS", "Sponsorship letter", "Your passport and proof of income", "Child's IELTS and academic documents"],
    faqs: [
      { q: "Can I show funds across multiple accounts?", a: "For UK visas, funds should be in one account or clearly documented." },
      { q: "When should I start saving?", a: "At least 1 month before visa application. Earlier is better." },
      { q: "Can my child work during study?", a: "UK: 20 hours/week. Canada: 20 hours/week. USA: limited on F-1." },
    ],
    cost_calculator_destination: null, cost_calculator_service_type: null,
    success_story_name: "Mrs. Funke A.", success_story_role: "Mother of 3 — two now studying in Canada",
    success_story_quote: "I saved for 2 years on Swiipt. The documented savings made the Canadian visa straightforward.",
    success_story_destination: "Lagos",
    meta_title: "Fund Your Child's International Education — Swiipt",
    meta_description: "Save for UK, Canada, USA, and Australia university fees. Build documented proof of funds for student visa applications.",
    published: false,
  },
  {
    slug: "maldives-honeymoon-package", url_prefix: "holiday", segment: "holiday_traveller",
    title: "Maldives Honeymoon Package — Save and Book",
    subtitle: "Save toward your Maldives honeymoon on Swiipt and book when you are ready.",
    hero_headline: "Your Maldives honeymoon. Planned and funded.",
    hero_subtext: "From ₦450,000 per person. All-inclusive. Return flights, overwater villa, transfers.",
    hero_cta_label: "Start my Maldives Fund", hero_cta_url: "/signup",
    destination: "Maldives", category: "holiday_package",
    process_steps: [
      { step: 1, title: "Choose your package", body: "4-night or 7-night options with flights, accommodation, and meals." },
      { step: 2, title: "Create your savings goal", body: "Save at your pace. Securely held until you book." },
      { step: 3, title: "Book when funded", body: "When your goal reaches 100%, book with one click." },
      { step: 4, title: "Travel documents", body: "No visa needed for Nigerians. Travel insurance recommended." },
    ],
    requirements: ["Valid passport — 6 months validity", "Return flight booking (included)", "Travel insurance (recommended)", "Yellow fever vaccination card"],
    faqs: [
      { q: "Do Nigerians need a visa?", a: "No. Free 30-day visa on arrival for Nigerian passport holders." },
      { q: "What is included?", a: "Return flights, accommodation, all meals, boat transfer, snorkelling equipment." },
      { q: "Can I customise?", a: "Yes. Contact us after creating your goal for upgrades and extras." },
    ],
    cost_calculator_destination: null, cost_calculator_service_type: null,
    success_story_name: "Amara and Tunde B.", success_story_role: "Married October 2025",
    success_story_quote: "We saved for 6 months on Swiipt and went to the Maldives. The package covered everything.",
    success_story_destination: "Maldives",
    meta_title: "Maldives Honeymoon Package for Nigerians — Save and Book | Swiipt",
    meta_description: "Save toward your Maldives honeymoon on Swiipt. All-inclusive packages from ₦450,000 per person. No visa required.",
    published: false,
  },
  {
    slug: "family-visa-reunification", url_prefix: "move", segment: "family_reunion",
    title: "Family Visa & Reunification — Bring Your Family Abroad",
    subtitle: "Already abroad? Bring your spouse, children, and parents to join you.",
    hero_headline: "Reunite your family. We handle the visa.",
    hero_subtext: "If you are in the UK, UAE, or Canada, we process your family's dependent or spousal visa.",
    hero_cta_label: "Start my Family Visa Fund", hero_cta_url: "/signup",
    destination: null, category: "work_visa",
    process_steps: [
      { step: 1, title: "Sponsor eligibility check", body: "We verify your salary meets the threshold for your country." },
      { step: 2, title: "Sponsorship documentation", body: "Proof of status, employment, and accommodation." },
      { step: 3, title: "Family application", body: "Passport, relationship certificates, photographs, financial documents." },
      { step: 4, title: "Submission and decision", body: "At relevant embassy. UK: 12 weeks, UAE: 4–8 weeks, Canada: 12–16 months." },
    ],
    requirements: ["Sponsor: proof of status, salary slips, bank statements, accommodation", "Family member: valid passport, relationship proof, police clearance, photographs"],
    faqs: [
      { q: "What is the UK salary requirement?", a: "£29,000/year minimum to sponsor a spouse." },
      { q: "Can I sponsor my parents?", a: "UK, Canada, and USA have very limited parent sponsorship routes." },
      { q: "How long is the separation?", a: "UK spousal: ~12 weeks. UAE dependent: 4–8 weeks. Canada spousal: 12–16 months." },
    ],
    cost_calculator_destination: null, cost_calculator_service_type: null,
    success_story_name: "Emeka O.", success_story_role: "UK resident since 2023",
    success_story_quote: "I spent 14 months separated from my wife. Swiipt brought her visa through in 11 weeks.",
    success_story_destination: "London, UK",
    meta_title: "Family Visa & Reunification for Nigerians Abroad — Swiipt",
    meta_description: "Bring your family to join you in the UK, UAE, or Canada. Spousal and dependent visa processing managed from Nigeria.",
    published: false,
  },
  {
    slug: "global-income-setup-remote-workers", url_prefix: "remote", segment: "remote_worker",
    title: "Global Income Setup for Nigerian Remote Workers",
    subtitle: "UK company, international banking, and income structure for Nigerians earning in foreign currency.",
    hero_headline: "You earn in USD or GBP. Let's make sure your income structure works properly.",
    hero_subtext: "Thousands of Nigerians work remotely for foreign companies. We build a proper structure: company, banking, and basic compliance.",
    hero_cta_label: "Start my Global Income Setup", hero_cta_url: "/signup",
    destination: null, category: "company_registration",
    process_steps: [
      { step: 1, title: "Income structure assessment", body: "We review how you receive payments and identify risks." },
      { step: 2, title: "UK company registration", body: "Register your UK Ltd company for invoicing foreign clients." },
      { step: 3, title: "International banking setup", body: "Wise Business for multi-currency. Optional: Mercury (US)." },
      { step: 4, title: "Annual compliance guidance", body: "Connect with a tax advisor for annual filing." },
    ],
    requirements: ["Valid passport", "Description of your remote work", "Details of current payment method", "List of countries invoiced"],
    faqs: [
      { q: "Is it legal to receive foreign income in Nigeria?", a: "Yes. There is no Nigerian law prohibiting foreign income." },
      { q: "Do I need to tell my Nigerian bank?", a: "This depends on how you receive it. We advise during assessment." },
      { q: "What does annual compliance involve?", a: "Companies House confirmation statement (£34) and company tax return." },
    ],
    cost_calculator_destination: null, cost_calculator_service_type: null,
    success_story_name: "Simi A.", success_story_role: "Freelance Copywriter earning in USD and GBP",
    success_story_quote: "Swiipt set up a UK company and Wise account in a week. My income is now properly structured.",
    success_story_destination: "Lagos",
    meta_title: "Global Income Setup for Nigerian Remote Workers — Swiipt",
    meta_description: "UK company registration, international banking, and income structure for Nigerians earning foreign currency remotely.",
    published: false,
  },
  {
    slug: "corporate-staff-relocation", url_prefix: "corporate", segment: "corporate",
    title: "Corporate Staff Relocation — International Mobility for Nigerian Companies",
    subtitle: "Visa processing, travel, and relocation coordination for companies sending staff abroad.",
    hero_headline: "Send your team internationally. We handle the paperwork.",
    hero_subtext: "From one visa to a retainer covering all your international staff movements.",
    hero_cta_label: "Talk to our corporate team", hero_cta_url: "/signup",
    destination: null, category: "relocation_concierge",
    process_steps: [
      { step: 1, title: "Retainer assessment", body: "We assess your volume and build pricing. Per-case or monthly retainer." },
      { step: 2, title: "HR system integration", body: "Document checklists, timelines, and communication protocols." },
      { step: 3, title: "Case management", body: "Dedicated case manager per staff relocation." },
      { step: 4, title: "Monthly reporting", body: "Status report covering all active cases to your HR director." },
    ],
    requirements: ["Company registration certificate", "HR contact person details", "Staff passport and contract", "Destination country requirements"],
    faqs: [
      { q: "What is included?", a: "Visa processing, document management, embassy appointments, dedicated case manager." },
      { q: "How is pricing structured?", a: "Per-case for occasional movers. Monthly retainer for 6+/year." },
      { q: "Do you cover all destinations?", a: "Yes. UAE, UK, Canada, Qatar, Germany, USA, and more." },
    ],
    cost_calculator_destination: null, cost_calculator_service_type: null,
    success_story_name: "Adeyemi B.", success_story_role: "HR Director, Lagos-based energy company",
    success_story_quote: "Swiipt put everything on one retainer. One contact, consistent quality, monthly reporting.",
    success_story_destination: "Lagos",
    meta_title: "Corporate Staff Relocation Nigeria — International Mobility | Swiipt",
    meta_description: "Visa processing and relocation management for Nigerian companies with international staff movement. Retainer pricing.",
    published: false,
  },
];

export async function POST(request: NextRequest) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: role } = await (supabase as any)
    .from("user_roles").select("role").eq("user_id", user.id).single();
  if (!role || role.role !== "admin") return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const { count } = await supabase
    .from("niche_pages")
    .select("*", { count: "exact", head: true });

  if (count && count > 0) {
    return NextResponse.json({ error: `${count} pages already exist. Delete them first if you want to re-seed.` }, { status: 400 });
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data: inserted, error: insertError } = await (supabase as any)
    .from("niche_pages")
    .insert(PAGES)
    .select("id");

  if (insertError) {
    return NextResponse.json({ error: "Seeding failed: " + insertError.message }, { status: 500 });
  }

  return NextResponse.json({ count: inserted?.length || 0 });
}
