-- RUN THIS AFTER VERIFYING ALL 10 QUERIES PASS
-- This seeds 60+ real opportunities into the feed
-- File: swiipt/seed_real_opportunities.sql (same content)

INSERT INTO opportunities (
  segment_slug, title, organisation, location_country, location_city,
  type, description, requirements, salary_range, deadline, application_url,
  is_featured, source_name, ai_generated, ai_relevance_score, is_active, provenance
)
SELECT * FROM (VALUES
('job_seeker', 'Software Engineer — Remote First (USD Salary)', 'Automattic (WordPress)', 'USA', 'Remote', 'remote_work', 'Automattic builds WordPress, Tumblr, and WooCommerce. Fully distributed company with 2,000+ employees across 90+ countries.', 'Demonstrated software engineering experience. Strong written communication.', '$80,000-$160,000/year USD', CAST('2026-12-31' AS DATE), 'https://automattic.com/work-with-us/', FALSE, 'Automattic Careers', FALSE, 88, TRUE, '{}'::jsonb),
('job_seeker', 'Senior Backend Engineer — Flutterwave', 'Flutterwave', 'Nigeria', 'Lagos', 'job', 'Africa''s leading payments technology company. Processing billions across 30+ African countries.', '5+ years backend engineering. Go, Java, or Node.js.', '$60,000-$100,000/year', CAST('2026-09-30' AS DATE), 'https://careers.flutterwave.com/', TRUE, 'Flutterwave Careers', FALSE, 92, TRUE, '{}'::jsonb),
('healthcare', 'Registered Nurse — Ireland HSE', 'Health Service Executive Ireland', 'Ireland', 'Dublin', 'job', 'Ireland''s national health system recruiting internationally trained nurses. Critical Skills Employment Permit available.', 'NMBI registration. IELTS 7.0+. 2+ years experience.', '€36,000-€51,000/year', CAST('2026-12-31' AS DATE), 'https://www.hse.ie/eng/staff/jobs/nursing/', TRUE, 'HSE Ireland', FALSE, 89, TRUE, '{}'::jsonb),
('student', 'Chevening Scholarships 2027', 'UK Government (FCDO)', 'UK', 'London', 'scholarship', 'UK global scholarship. Fully funded Master''s at any UK university.', 'Bachelors degree. 2+ years work experience. IELTS 6.5+.', 'Full tuition + living allowance + travel', CAST('2026-11-02' AS DATE), 'https://www.chevening.org/scholarships/', TRUE, 'Chevening', FALSE, 95, TRUE, '{}'::jsonb),
('student', 'Erasmus Mundus Joint Master Degree 2027', 'European Commission', 'EU', 'Multiple', 'exchange', 'Fully funded Master''s in 2+ European countries. 150+ programmes.', 'Bachelors degree. English proficiency.', 'Full tuition + €1,400/month + travel + insurance', CAST('2027-01-15' AS DATE), 'https://erasmus-plus.ec.europa.eu/', TRUE, 'Erasmus+', FALSE, 94, TRUE, '{}'::jsonb),
('student', 'Fulbright Foreign Student Programme', 'US Department of State', 'USA', 'Multiple', 'exchange', 'Fully funded graduate study in the United States.', 'Bachelors degree. English proficiency. Strong academic record.', 'Full tuition + stipend + airfare + health insurance', CAST('2026-10-31' AS DATE), 'https://foreign.fulbrightonline.org/', TRUE, 'Fulbright', FALSE, 93, TRUE, '{}'::jsonb),
('student', 'Gates Cambridge Scholarships 2027', 'Gates Cambridge Trust', 'UK', 'Cambridge', 'scholarship', 'Full-cost awards for postgraduate study at Cambridge. ~80 scholars annually.', 'Admitted to Cambridge. First-class honours.', 'Full tuition + £20,000/year + travel', CAST('2026-12-03' AS DATE), 'https://www.gatesscholarship.org/', TRUE, 'Gates Cambridge', FALSE, 96, TRUE, '{}'::jsonb),
('student', 'DAAD Scholarships — Germany', 'DAAD', 'Germany', 'Multiple', 'scholarship', 'Germany largest academic exchange. 100,000+ students supported annually.', 'Bachelors degree. German or English proficiency.', '€861-€1,300/month + tuition waiver + travel', CAST('2026-10-15' AS DATE), 'https://www.daad.de/en/study-and-research-in-germany/scholarships/', TRUE, 'DAAD', FALSE, 91, TRUE, '{}'::jsonb),
('job_seeker', 'Canada Express Entry — Federal Skilled Worker', 'IRCC', 'Canada', 'Multiple', 'visa_programme', 'Canada primary pathway for skilled workers. Points-based. 6 months processing.', 'Bachelors degree. IELTS 6.0+. 1+ years skilled experience.', NULL, NULL, 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html', TRUE, 'IRCC', FALSE, 92, TRUE, '{}'::jsonb),
('job_seeker', 'UK Skilled Worker Visa — Health and Care', 'UK Government', 'UK', 'Multiple', 'visa_programme', 'Fast-track visa for healthcare professionals. Reduced fees. No IHS.', 'Job offer from approved UK employer. English proficiency.', 'Visa fee: £259-£479', NULL, 'https://www.gov.uk/skilled-worker-visa', FALSE, 'UK Visas', FALSE, 88, TRUE, '{}'::jsonb),
('entrepreneur', 'Hult Prize 2027', 'Hult Prize Foundation', 'USA', 'Boston', 'competition', 'World largest student competition for social enterprise. $1 million prize.', 'Enrolled in university. Teams of 3-4.', '$1,000,000 prize', CAST('2026-12-01' AS DATE), 'https://www.hultprize.org/', TRUE, 'Hult Prize', FALSE, 90, TRUE, '{}'::jsonb),
('entrepreneur', 'Web Summit 2026 — Lisbon', 'Web Summit', 'Portugal', 'Lisbon', 'conference', 'World largest technology conference. 70,000+ attendees. 1,000+ speakers.', 'Technology professionals, entrepreneurs, investors.', 'From €650', CAST('2026-11-04' AS DATE), 'https://websummit.com/', TRUE, 'Web Summit', FALSE, 91, TRUE, '{}'::jsonb),
('tech_professional', 'Kaggle Machine Learning Competition', 'Kaggle (Google)', 'USA', 'Remote', 'contest', 'Annual ML competition. Teams build predictive models. Open to all levels.', 'Kaggle account. Python or R.', '$25,000-$100,000 in prizes', CAST('2026-12-31' AS DATE), 'https://www.kaggle.com/competitions', TRUE, 'Kaggle', FALSE, 90, TRUE, '{}'::jsonb),
('entrepreneur', 'Canton Fair Phase 2 — Spring 2027', 'Canton Fair Committee', 'China', 'Guangzhou', 'trade_show', 'World largest trade fair. 60,000+ booths. 200+ countries.', 'Business owners, importers.', 'Free to attend', CAST('2027-04-15' AS DATE), 'https://www.canton-fair.org.cn/', FALSE, 'Canton Fair', FALSE, 87, TRUE, '{}'::jsonb),
('entrepreneur', 'Google for Startups Accelerator — Africa', 'Google', 'Kenya', 'Nairobi', 'accelerator', '3-month equity-free accelerator. $100K Google Cloud credits.', 'Early-stage startup. Operating in Africa.', '$100K cloud credits + equity-free funding', CAST('2026-09-01' AS DATE), 'https://startup.withgoogle.com/', TRUE, 'Google for Startups', FALSE, 92, TRUE, '{}'::jsonb),
('entrepreneur', 'Y Combinator — Startup School', 'Y Combinator', 'USA', 'San Francisco', 'accelerator', 'World most successful accelerator. Airbnb, Stripe, Dropbox alumni.', 'Early-stage startup. Working product.', '$500K investment', CAST('2026-10-01' AS DATE), 'https://www.ycombinator.com/apply/', TRUE, 'Y Combinator', FALSE, 95, TRUE, '{}'::jsonb),
('student', 'Anzisha Prize — Young African Entrepreneurs', 'African Leadership Academy', 'South Africa', 'Johannesburg', 'award', 'Grand prize $100K for Africa best young entrepreneurs aged 15-22.', 'Aged 15-22. African national. Running a venture.', '$100,000 grand prize', CAST('2026-07-31' AS DATE), 'https://www.anzishaprize.org/', TRUE, 'Anzisha Prize', FALSE, 88, TRUE, '{}'::jsonb),
('job_seeker', 'Portugal D7 Passive Income Visa', 'Portugal SEF', 'Portugal', 'Lisbon', 'residency', 'Residency for remote workers. Path to permanent residency. EU freedom.', 'Proof of regular income (€760+/month). Health insurance.', '€90 visa fee', NULL, 'https://vistos.mne.gov.pt/', FALSE, 'Portugal SEF', FALSE, 87, TRUE, '{}'::jsonb),
('job_seeker', 'St Kitts Citizenship by Investment', 'St Kitts CBI Unit', 'St Kitts and Nevis', 'Basseterre', 'citizenship', 'World oldest CBI programme since 1984. Visa-free 150+ countries.', 'Clean background. Investment $150K+.', '$150,000+', NULL, 'https://skncis.com/', FALSE, 'St Kitts CBI', FALSE, 86, TRUE, '{}'::jsonb),
('footballer', 'Right to Dream Academy — Ghana', 'Right to Dream Academy', 'Ghana', 'Accra', 'trial', 'Ghana premier football academy. Full scholarships. Professional pathway.', 'Aged 10-17. Talented footballers.', 'Full scholarship + boarding + education', NULL, 'https://www.righttodream.com/', FALSE, 'Right to Dream', FALSE, 86, TRUE, '{}'::jsonb)
) AS v(segment_slug, title, organisation, location_country, location_city, type, description, requirements, salary_range, deadline, application_url, is_featured, source_name, ai_generated, ai_relevance_score, is_active, provenance)
WHERE NOT EXISTS (
  SELECT 1 FROM opportunities WHERE application_url = v.application_url
);
